## 1113. Reported Posts

**Solved**

**Easy**

### Topics
- Companies
- SQL Schema
- Pandas Schema

### Table: Actions

| Column Name | Type    |
|-------------|---------|
| user_id     | int     |
| post_id     | int     |
| action_date | date    |
| action      | enum    |
| extra       | varchar |

This table may have duplicate rows.
The `action` column is an ENUM (category) type of ('view', 'like', 'reaction', 'comment', 'report', 'share').
The `extra` column has optional information about the action, such as a reason for the report or a type of reaction.
`extra` is never NULL.

Write a solution to report the number of posts reported yesterday for each report reason. Assume today is 2019-07-05.

Return the result table in any order.

The result format is in the following example.

### Example 1:

**Input:**
Actions table:
| user_id | post_id | action_date | action | extra  |
|---------|---------|-------------|--------|--------|
| 1       | 1       | 2019-07-01  | view   | null   |
| 1       | 1       | 2019-07-01  | like   | null   |
| 1       | 1       | 2019-07-01  | share  | null   |
| 2       | 4       | 2019-07-04  | view   | null   |
| 2       | 4       | 2019-07-04  | report | spam   |
| 3       | 4       | 2019-07-04  | view   | null   |
| 3       | 4       | 2019-07-04  | report | spam   |
| 4       | 3       | 2019-07-02  | view   | null   |
| 4       | 3       | 2019-07-02  | report | spam   |
| 5       | 2       | 2019-07-04  | view   | null   |
| 5       | 2       | 2019-07-04  | report | racism |
| 5       | 5       | 2019-07-04  | view   | null   |
| 5       | 5       | 2019-07-04  | report | racism |

**Output:**
| report_reason | report_count |
|---------------|--------------|
| spam          | 1            |
| racism        | 2            |

Explanation: Note that we only care about report reasons with non-zero number of reports.

In [1]:
import pandas as pd

In [2]:
def reported_posts(actions: pd.DataFrame) -> pd.DataFrame:

    yesterday_actions = actions[actions['action_date'] == '2019-07-04']
    filtered_actions = yesterday_actions[yesterday_actions['action'] == 'report'].drop_duplicates(['post_id','extra']).value_counts('extra')

    return pd.DataFrame({'report_reason':filtered_actions.index.to_list(),
                'report_count':filtered_actions.values})

In [3]:
actions = pd.DataFrame([
    {"user_id": 1, "post_id": 1, "action_date": "2019-07-01", "action": "view", "extra": None},
    {"user_id": 1, "post_id": 1, "action_date": "2019-07-01", "action": "like", "extra": None},
    {"user_id": 1, "post_id": 1, "action_date": "2019-07-01", "action": "share", "extra": None},
    {"user_id": 2, "post_id": 4, "action_date": "2019-07-04", "action": "view", "extra": None},
    {"user_id": 2, "post_id": 4, "action_date": "2019-07-04", "action": "report", "extra": "nudity"},
    {"user_id": 3, "post_id": 4, "action_date": "2019-07-04", "action": "view", "extra": None},
    {"user_id": 3, "post_id": 4, "action_date": "2019-07-04", "action": "report", "extra": "spam"},
    {"user_id": 4, "post_id": 3, "action_date": "2019-07-02", "action": "view", "extra": None},
    {"user_id": 4, "post_id": 3, "action_date": "2019-07-02", "action": "report", "extra": "spam"},
    {"user_id": 5, "post_id": 2, "action_date": "2019-07-04", "action": "view", "extra": None},
    {"user_id": 5, "post_id": 2, "action_date": "2019-07-04", "action": "report", "extra": "racism"},
    {"user_id": 5, "post_id": 5, "action_date": "2019-07-04", "action": "view", "extra": None},
    {"user_id": 5, "post_id": 5, "action_date": "2019-07-04", "action": "report", "extra": "fake"}
])

reported_posts(actions=actions)

  report_reason  report_count
0          fake             1
1        nudity             1
2        racism             1
3          spam             1

In [4]:
actions = pd.DataFrame({
    "user_id": [1, 1, 1, 2, 2, 3, 3, 4, 4, 5, 5, 5, 5],
    "post_id": [1, 1, 1, 4, 4, 4, 4, 3, 3, 2, 2, 5, 5],
    "action_date": ["2019-07-01", "2019-07-01", "2019-07-01", "2019-07-04", "2019-07-04", "2019-07-04", "2019-07-04", "2019-07-02", "2019-07-02", "2019-07-04", "2019-07-04", "2019-07-04", "2019-07-04"],
    "action": ["view", "like", "share", "view", "report", "view", "report", "view", "report", "view", "report", "view", "report"],
    "extra": [None, None, None, None, "spam", None, "spam", None, "spam", None, "racism", None, "racism"]
}
)

reported_posts(actions=actions)

  report_reason  report_count
0        racism             2
1          spam             1